__version__ = "0.2.2"
APP_NAME = "Super DL"
APP_AUTHOR = "Sergio Adam"
APP_HOMEPAGE = "https://github.com/SerxUp/super-dl"
APP_ISSUES_URL = "https://github.com/SerxUp/super-dl/issues"
GITHUB_REPO = "SerxUp/super-dl"
